name: Py Scraper 
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scraper:
    name: Py Scraper 
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11

      - name: Cache Python packages
        uses: actions/cache@main
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download APKTool
        run: |
          curl -O https://raw.githubusercontent.com/iBotPeaches/Apktool/master/apktool.jar
          echo "apktool.jar downloaded."

      - name: Download aapt2
        run: |
          # Tải xuống aapt2 từ Android SDK Build Tools (ví dụ phiên bản 30.0.3)
          curl -L -o aapt2.zip https://dl.google.com/android/repository/build-tools/30.0.3/aapt2
          chmod +x aapt2
          mv aapt2 /usr/local/bin/
          echo "aapt2 downloaded and installed."

      - name: Run Scraper 
        run: python main.py

      - name: Upload Merged APK as artifact
        uses: actions/upload-artifact@main
        with:
          name: merged-apk
          path: ./merged_apks/merged_app.apk # Đảm bảo đường dẫn đúng tới APK hợp nhất
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
